apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: udacityshop-dev
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-options: Validate=false
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: default
  source:
    # path to the folder with the YAML manifests
    path: kubernetes-manifests/dev
    repoURL: https://github.com/ramirezalfredo/nd064_capstone_starter
    targetRevision: HEAD
  # Sync policy
  syncPolicy:
    automated: {}