name: Uda'CityShop [latest tag] - Package with Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: aramirezg/frontend:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/productcatalogservice/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: aramirezg/productcatalogservice:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/currencyservice/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: aramirezg/currencyservice:latest
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./src/adservice/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: aramirezg/adservice:latest
      # -
      #   name: Image digest
      #   run: echo ${{ steps.docker_build.outputs.digest }}