name: Uda'CityShop [sha tag] - Package with Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Docker meta
        id: meta-frontend
        uses: docker/metadata-action@v3
        with:
          images: aramirezg/frontend
          tags: type=sha
      -
        name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ./src/frontend
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
      -
        name: Docker meta
        id: meta-productcatalogservice
        uses: docker/metadata-action@v3
        with:
          images: aramirezg/productcatalogservice
          tags: type=sha
      -
        name: Build and push productcatalogservice
        uses: docker/build-push-action@v2
        with:
          context: ./src/productcatalogservice
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta-productcatalogservice.outputs.tags }}
      -
        name: Docker meta
        id: meta-currencyservice
        uses: docker/metadata-action@v3
        with:
          images: aramirezg/currencyservice
          tags: type=sha
      -
        name: Build and push currencyservice
        uses: docker/build-push-action@v2
        with:
          context: ./src/currencyservice
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta-currencyservice.outputs.tags }}
      -
        name: Docker meta
        id: meta-adservice
        uses: docker/metadata-action@v3
        with:
          images: aramirezg/adservice
          tags: type=sha
      -
        name: Build and push adservice
        uses: docker/build-push-action@v2
        with:
          context: ./src/adservice
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta-adservice.outputs.tags }}
